function(link_dnnl visibility target_name)
    if(ENABLE_DNNL)
        if(TARGET DNNL::dnnl)
            target_link_libraries(${target_name} ${visibility} DNNL::dnnl)
        else()
            target_include_directories(${target_name} ${visibility} ${DNNL_INCLUDE_DIRS})
            target_link_libraries(${target_name} ${visibility} ${DNNL_LIBRARIES})
            if(NOT MSVC)
                target_link_libraries(${target_name} ${visibility} pthread m dl)
            endif()
        endif()

        if(TARGET TBB::tbb)
            target_compile_definitions(${target_name} ${visibility} DNNL_CPU_RUNTIME=DNNL_RUNTIME_TBB)
            message(STATUS "oneDNN CPU runtime: TBB (via CMake config)")
        endif()

        if(ENABLE_MKL)
            target_compile_definitions(${target_name} ${visibility} ONEDNN_BLAS_VENDOR=ONEDNN_BLAS_MKL)
        endif()

        if(DNNL_INTEL_RUNTIME_LIB_DIR)
            target_link_directories(${target_name} ${visibility} "${DNNL_INTEL_RUNTIME_LIB_DIR}")
            if(NOT MSVC)
                target_link_options(${target_name} ${visibility}
                    "LINKER:--disable-new-dtags"
                    "LINKER:-rpath,${DNNL_INTEL_RUNTIME_LIB_DIR}")
            endif()
        endif()
        if(DNNL_INTEL_RUNTIME_LIBS)
            target_link_libraries(${target_name} ${visibility} ${DNNL_INTEL_RUNTIME_LIBS})
        endif()
    endif()
endfunction()
